table:
  name: c01
  header: 1
  delimiter: ","
  encoding: UTF8
  location: "sandbox/c01/"
columns:
  - name: prefecture_code
    type: string
  - name: prefecture_name
    type: string
  - name: gen
    type: string
  - name: japanese_year
    type: int
  - name: western_year
    type: int
  - name: note
    type: string
  - name: population_total
    type: bigint
  - name: population_male
    type: bigint
  - name: population_female
    type: bigint
